package com.exercise.demo.mybatis.dao;

import com.exercise.demo.mybatis.dto.ImUserDto;

public interface ImUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user
     *
     * @mbg.generated
     */
    int insert(ImUserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user
     *
     * @mbg.generated
     */
    int insertSelective(ImUserDto record);
}