package com.exercise.demo.mybatis.dto;

import lombok.Data;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table im_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class ImUserDto {
    /**
     * Database Column Remarks:
     * 主键id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     * uuid
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     * 用户名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     * 用户密码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user.user_password
     *
     * @mbg.generated
     */
    private String userPassword;

}